# Generated by Django 4.2.19 on 2025-03-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_struct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип файла',
                'verbose_name_plural': 'Типы файлов',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(help_text='Загрузите документ', upload_to='doc/')),
                ('actual', models.BooleanField(default=True, help_text='Актуально', verbose_name='Актуально')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создан', verbose_name='Создан')),
                ('from_send', models.TextField(blank=True, help_text='Откуда пришел документ: company-2-comment-3', null=True, verbose_name='Откуда пришел документ')),
                ('type', models.ForeignKey(blank=True, help_text='Тип файла', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='app_doc.filetype', verbose_name='Тип файла')),
                ('user_created', models.ForeignKey(help_text='Сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('esk', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Компания', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to='app_struct.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(blank=True, help_text='Контрагент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='app_doc.contractor', verbose_name='Контрагент')),
                ('file', models.ForeignKey(blank=True, help_text='Документ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='app_doc.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
