# Generated by Django 4.2.19 on 2025-03-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user_created',
        ),
    ]
