# Generated by Django 4.2.19 on 2025-03-31 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0001_initial'),
        ('app_doc', '0002_remove_document_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user_created',
            field=models.ForeignKey(blank=True, help_text='Сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.employee', verbose_name='Сотрудник'),
        ),
    ]
