# Generated by Django 4.2.19 on 2025-04-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0003_comment_project'),
        ('app_doc', '0003_document_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_comments.comment'),
        ),
    ]
