# Generated by Django 4.2.19 on 2025-04-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0004_document_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='comment',
        ),
    ]
