# Generated by Django 4.2.19 on 2025-04-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.CharField(choices=[('low', 'Низкая'), ('middle', 'Средняя'), ('high', 'Высокая')], default='Средняя', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not', 'Не начата'), ('worked', 'В работе'), ('cancel', 'Отмена'), ('ended', 'Завершена')], max_length=50),
        ),
    ]
