# Generated by Django 4.2.19 on 2025-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0002_alter_task_importance_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not', 'Не начата'), ('worked', 'В работе'), ('canceled', 'Отмена'), ('ended', 'Завершена')], max_length=50),
        ),
    ]
