# Generated by Django 4.2.19 on 2025-04-28 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fact_dev_cost',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='fact_dev_dt',
            field=models.DateField(blank=True, help_text='Дата освоения', null=True, verbose_name='Дата освоения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fact_fin_cost',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='fact_fin_dt',
            field=models.DateField(blank=True, help_text='Дата оплаты', null=True, verbose_name='Дата оплаты'),
        ),
    ]
