# Generated by Django 4.2.19 on 2025-04-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0004_alter_task_fact_dev_cost_alter_task_fact_dev_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancost',
            name='ndfl_bool',
        ),
        migrations.RemoveField(
            model_name='plancost',
            name='nds_bool',
        ),
    ]
