# Generated by Django 4.2.19 on 2025-04-28 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0005_remove_plancost_ndfl_bool_remove_plancost_nds_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancost',
            name='ndfl',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plancost',
            name='nds',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plancost',
            name='plan_dev_cost',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plancost',
            name='plan_dev_dt',
            field=models.DateField(blank=True, help_text='Плановая дата освоения', null=True, verbose_name='Плановая дата освоения'),
        ),
        migrations.AlterField(
            model_name='plancost',
            name='plan_fin_cost',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='plancost',
            name='plan_fin_dt',
            field=models.DateField(blank=True, help_text='Плановая дата оплаты', null=True, verbose_name='Плановая дата оплаты'),
        ),
    ]
