# Generated by Django 4.2.19 on 2025-05-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0006_alter_plancost_ndfl_alter_plancost_nds_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancost',
            options={'verbose_name': 'Плановая оплата', 'verbose_name_plural': 'Плановые оплаты'},
        ),
        migrations.AlterModelOptions(
            name='plandateend',
            options={'verbose_name': 'Плановая дата завершения задачи', 'verbose_name_plural': 'Плановые даты завершения задачи'},
        ),
        migrations.AlterModelOptions(
            name='plandatestart',
            options={'verbose_name': 'Плановая дата начала задачи', 'verbose_name_plural': 'Плановые даты начала задачи'},
        ),
    ]
