# Generated by Django 4.2.19 on 2025-03-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_econ', '0001_initial'),
        ('app_struct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Краткие сведения', verbose_name='Краткие сведения')),
                ('full_name', models.TextField(help_text='Полный комментарий', verbose_name='Полный комментарий')),
                ('created', models.DateTimeField(auto_now=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('actual', models.BooleanField(default=True, help_text='Актуальность', verbose_name='Актуальность')),
                ('files_id', models.TextField(blank=True, help_text='ID файлов', null=True, verbose_name='ID файлов')),
                ('company', models.ForeignKey(blank=True, help_text='Компания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.company', verbose_name='Компания')),
                ('division', models.ForeignKey(blank=True, help_text='Подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.division', verbose_name='Подразделение')),
                ('facility', models.ForeignKey(blank=True, help_text='Объект', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.facility', verbose_name='Объект')),
                ('license', models.ForeignKey(blank=True, help_text='Лицензионный участок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.license', verbose_name='Лицензионный участок')),
                ('project', models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_econ.project', verbose_name='Проект')),
                ('user_created', models.ForeignKey(help_text='Сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
