# Generated by Django 4.2.19 on 2025-03-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0001_initial'),
        ('app_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_created',
            field=models.ForeignKey(help_text='Сотрудник', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_struct.employee', verbose_name='Сотрудник'),
        ),
    ]
