# Generated by Django 4.2.19 on 2025-04-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
    ]
