# Generated by Django 4.2.19 on 2025-04-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_econ', '0001_initial'),
        ('app_comments', '0002_remove_comment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Проект', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_econ.project', verbose_name='Проект'),
        ),
    ]
