# Generated by Django 4.2.19 on 2025-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0005_remove_document_comment'),
        ('app_comments', '0003_comment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Документы, связанные с этим комментарием', related_name='comments', to='app_doc.document'),
        ),
    ]
