# Generated by Django 5.1.4 on 2025-01-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250, unique=True, verbose_name='Наименование')),
                ('full_name', models.CharField(help_text='Полное наименование', max_length=250, verbose_name='Полное наименование')),
                ('logo', models.ImageField(blank=True, help_text='Логотип', null=True, upload_to='struct/company/logo/', verbose_name='Логотип')),
                ('contacts', models.TextField(blank=True, help_text='Контакты', null=True, verbose_name='Контакты')),
                ('note', models.TextField(blank=True, help_text='Примечание', null=True, verbose_name='Примечание')),
                ('actual', models.BooleanField(default=True, help_text='Актуальна', verbose_name='Актуальна')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создан', verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Обновлен', verbose_name='Обновлен')),
                ('gis', models.TextField(blank=True, help_text='GIS ID', null=True, verbose_name='GIS ID')),
                ('parent', models.ForeignKey(blank=True, help_text='Головная компания', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcompany', to='app_struct.company', verbose_name='Головная компания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='app_struct__name_988ba9_idx')],
            },
        ),
    ]
