# Generated by Django 5.1.4 on 2025-01-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0002_alter_company_gis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Головная компания', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcompany', to='app_struct.company', verbose_name='Головная'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250, verbose_name='Наименование')),
                ('abbr', models.CharField(help_text='Аббревиатура', max_length=17, verbose_name='Аббревиатура')),
                ('contacts', models.TextField(blank=True, help_text='Контакты', null=True, verbose_name='Контакты')),
                ('note', models.TextField(blank=True, help_text='Примечание', null=True, verbose_name='Примечание')),
                ('actual', models.BooleanField(default=True, help_text='Актуально', verbose_name='Актуально')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создан', verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Обновлен', verbose_name='Обновлен')),
                ('company', models.ForeignKey(help_text='Компания', on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='app_struct.company', verbose_name='Компания')),
                ('parent', models.ForeignKey(blank=True, help_text='Руководящее подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisions', to='app_struct.division', verbose_name='Руководящее')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['company', 'name'],
                'indexes': [models.Index(fields=['name'], name='app_struct__name_28d021_idx')],
                'unique_together': {('company', 'abbr'), ('company', 'name')},
            },
        ),
    ]
