# Generated by Django 5.1.4 on 2025-01-27 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0003_alter_company_parent_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя', max_length=250, verbose_name='Имя')),
                ('surname', models.CharField(help_text='Фамилия', max_length=250, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, help_text='Отчество', max_length=250, null=True, verbose_name='Отчество')),
                ('post', models.CharField(help_text='Должность', max_length=250, verbose_name='Должность')),
                ('phone', models.CharField(help_text='Телефон', max_length=250, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта', max_length=250, null=True, verbose_name='Почта')),
                ('avatar', models.ImageField(blank=True, help_text='Аватар', null=True, upload_to='struct/employee/ava/', verbose_name='Аватар')),
                ('is_director', models.BooleanField(default=False, help_text='Руководитель', verbose_name='Руководитель')),
                ('date_birth', models.DateField(blank=True, help_text='Дата рождения', null=True, verbose_name='Дата рождения')),
                ('contacts', models.TextField(blank=True, help_text='Контактная информация', null=True, verbose_name='Контакт')),
                ('note', models.TextField(blank=True, help_text='Примечание', null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создан', verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Обновлен', verbose_name='Обновлен')),
                ('company', models.ForeignKey(help_text='Компания', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app_struct.company', verbose_name='Компания')),
                ('division', models.ForeignKey(blank=True, help_text='Подразделение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app_struct.division', verbose_name='Подразделение')),
                ('user', models.OneToOneField(blank=True, help_text='Пользователь системы', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['surname', 'name', 'patronymic'],
                'indexes': [models.Index(fields=['surname'], name='app_struct__surname_45b931_idx')],
                'unique_together': {('surname', 'name', 'patronymic', 'company', 'post')},
            },
        ),
    ]
