# Generated by Django 5.1.4 on 2025-01-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0004_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['surname', 'name', 'patronymic'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=250, unique=True, verbose_name='Наименование')),
                ('dt_start', models.DateField(help_text='Начало', verbose_name='Начало')),
                ('dt_end', models.DateField(help_text='Окончание', verbose_name='Окончание')),
                ('doc', models.FileField(blank=True, help_text='Файл лицензии', null=True, upload_to='doc/license/', verbose_name='Лицензия')),
                ('note', models.TextField(blank=True, help_text='Примечание', null=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Создан', verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Обновлен', verbose_name='Обновлен')),
                ('gis', models.CharField(blank=True, help_text='GIS ID', max_length=255, null=True, verbose_name='GIS ID')),
                ('owner', models.ForeignKey(blank=True, help_text='Владелец', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to='app_struct.company', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
                'ordering': ['owner', 'name'],
                'indexes': [models.Index(fields=['name'], name='app_struct__name_9c31e5_idx')],
            },
        ),
    ]
