# Generated by Django 5.1.4 on 2025-01-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0005_alter_employee_options_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='actual',
            field=models.BooleanField(default=True, help_text='Актуально', verbose_name='Актуально'),
        ),
    ]
