# Generated by Django 5.1.4 on 2025-01-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_struct', '0007_facility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name'], 'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('parent', 'name')},
        ),
    ]
